version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123! # Root username is 'sa'
    ports:
      - "1433:1433"
      
    networks:
      - mssql-network

networks:
  mssql-network:
    driver: bridge