BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Allocations] ALTER COLUMN [Hotel_ID] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Allocations] ALTER COLUMN [Settelment_ID] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Allocations] ALTER COLUMN [Rooms] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
